<header>
    <h1>IPv4 &amp; IPv6</h1>
    <nav>
      <ul class="navbar">
        <li><a href="index.php">Home</a></li>
          <li><a href="topic1.php">Technology</a>
            <ul class="subnavbar">
              <li><a href="topic1.php">IPv4</a>
                <ul class="subnavbar2">
                  <li><a href="topic1.php#WhatisIPv4">What is IPv4?</a></li>
                  <li><a href="topic1.php#ipv4_add_str">Address Structure</a></li>
                  <li><a href="topic1.php#ipv4_add_class">Address Classes</a></li>
                  <li><a href="topic1.php#ipv4_add_type">Address Types</a></li>
                </ul>
              </li>
              <li><a href="topic2.php">IPv6</a>
                <ul class="subnavbar2">
                  <li><a href="topic2.php#WhatisIPv6">What is IPv6?</a></li>
                  <li><a href="topic2.php#ipv6_add_str">Address Structure</a></li>
                  <li><a href="topic2.php#ipv6_add_type">Address Types</a></li>
                </ul>
              </li>
              <li><a href="topic3.php">IPv4 vs IPv6</a>
                <ul class="subnavbar2">
                  <li><a href="topic3.php#limitation">Limitations of IPv4</a></li>
                  <li><a href="topic3.php#advantage">Advantages of IPv6</a></li>
                  <li><a href="topic3.php#difference">Differences</a></li>
                </ul>
              </li>
            </ul>
          </li>
          <li><a href="quiz.php">Quiz</a></li>
          <li><a href="manage.php">Quiz Records</a></li>
          <li><a href="phpenhancements.php">Enhancements</a>
            <ul class="subnavbar">
              <li><a href="enhancements.html">CSS</a></li>
              <li><a href="enhancements2.html">JavaScript</a></li>
              <li><a href="phpenhancements.php">PHP</a></li>
            </ul>
          </li>
        </ul>
      </nav>
</header>
